export const APP_URL = process.env.NEXT_PUBLIC_APP_URL!
export const MAIN_DOMAIN = process.env.NEXT_PUBLIC_MAIN_DOMAIN! || "ikazestores.com"
export const EXCHANGE_RATES_API_KEY = process.env.NEXT_PUBLIC_EXCHANGE_RATES_API_KEY

export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!
export const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!
export const SYSTEM_OPERATIONS_TEAM = process.env.NEXT_PUBLIC_SYSTEM_OPERATIONS_TEAM!

export const USER_DATA_ID = process.env.NEXT_PUBLIC_USER_DATA_ID!
export const PHYSICAL_STORE_ID = process.env.NEXT_PUBLIC_PHYSICAL_STORE_ID!
export const VIRTUAL_STORE_ID = process.env.NEXT_PUBLIC_VIRTUAL_STORE_ID!
export const VIRTUAL_SELLERS_TEAM_ID = process.env.NEXT_PUBLIC_VIRTUAL_SELLERS_TEAM_ID!
export const VIRTUAL_COMBINATION_PRICES_COLLECTION_ID = process.env.NEXT_PUBLIC_VIRTUAL_COMBINATION_PRICES!

export const STORE_BUCKET_ID = process.env.NEXT_PUBLIC_STORE_BUCKET_ID!
export const PRODUCTS_BUCKET_ID = process.env.NEXT_PUBLIC_PRODUCTS_BUCKET_ID!

export const ORIGINAL_PRODUCT_ID = process.env.NEXT_PUBLIC_ORIGINAL_PRODUCT_ID!
export const VIRTUAL_PRODUCT_ID = process.env.NEXT_PUBLIC_VIRTUAL_PRODUCT_ID!
export const ORDER_ID = process.env.NEXT_PUBLIC_ORDER_ID!
export const ORDER_ITEM_ID = process.env.NEXT_PUBLIC_ORDER_ITEM_ID!
export const DELIVERY_ADDRESS_ID = process.env.NEXT_PUBLIC_DELIVERY_ADDRESS_ID!
export const CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID!
export const SUB_CATEGORIES_ID = process.env.NEXT_PUBLIC_SUB_CATEGORIES_ID!
export const PRODUCTS_IMAGES_COLORS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCTS_IMAGES_COLORS_COLLECTION_ID!
export const PRODUCTS_COLLECTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCTS_COLLECTIONS_COLLECTION_ID!
export const PRODUCTS_COLLECTION_GROUPS_ID = process.env.NEXT_PUBLIC_PRODUCTS_COLLECTION_GROUPS_ID!
export const SAVED_ITEMS_COLLECTION_ID = process.env.NEXT_PUBLIC_SAVED_ITEMS_COLLECTION_ID!
export const PRODUCT_TYPES_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCT_TYPES_COLLECTION_ID!

export const PRODUCT_VARIANT_OPTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCT_VARIANT_OPTIONS_COLLECTION_ID!
export const PRODUCT_VARIANTS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCT_VARIANTS_COLLECTION_ID!
export const VARIANT_COMBINATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_VARIANT_COMBINATIONS_COLLECTION_ID!
export const VARIANT_COMBINATION_VALUES_COLLECTION_ID = process.env.NEXT_PUBLIC_VARIANT_COMBINATION_VALUES_COLLECTION_ID!
export const STORE_CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_STORE_CATEGORIES_COLLECTION_ID!




export const PRODUCTS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCTS_COLLECTION_ID!