export const APP_URL = process.env.NEXT_PUBLIC_APP_URL!
export const MAIN_DOMAIN = process.env.NEXT_PUBLIC_MAIN_DOMAIN! || "ikazestores.com"
export const APPWRITE_ENDPOINT =process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!
export const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!

export const USER_DATA_ID = process.env.NEXT_PUBLIC_USER_DATA_ID!
export const PHYSICAL_STORE_ID = process.env.NEXT_PUBLIC_PHYSICAL_STORE_ID!
export const VIRTUAL_STORE_ID = process.env.NEXT_PUBLIC_VIRTUAL_STORE_ID!
export const VIRTUAL_SELLERS_TEAM_ID = process.env.NEXT_PUBLIC_VIRTUAL_SELLERS_TEAM_ID!

export const STORE_BUCKET_ID = process.env.NEXT_PUBLIC_STORE_BUCKET_ID!
export const PRODUCTS_BUCKET_ID = process.env.NEXT_PUBLIC_PRODUCTS_BUCKET_ID!

export const ORIGINAL_PRODUCT_ID = process.env.NEXT_PUBLIC_ORIGINAL_PRODUCT_ID!
export const VIRTUAL_PRODUCT_ID = process.env.NEXT_PUBLIC_VIRTUAL_PRODUCT_ID!
export const ORDER_ID = process.env.NEXT_PUBLIC_ORDER_ID!
export const ORDER_ITEM_ID = process.env.NEXT_PUBLIC_ORDER_ITEM_ID!
export const DELIVERY_ADDRESS_ID = process.env.NEXT_PUBLIC_DELIVERY_ADDRESS_ID!
export const CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID!
export const SUB_CATEGORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_SUB_CATEGORIES_COLLECTION_ID!
export const PRODUCTS_IMAGES_COLORS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCTS_IMAGES_COLORS_COLLECTION_ID!
