import { type Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts Z:\DATA\ARSENE\2025\ikazestore-new\ikazestores`.

export enum AccountType {
    SYS_ADMIN = "sysAdmin",
    SYS_AGENT = "sysAgent",
    PHYSICAL_SELLER = "physicalSeller",
    VIRTUAL_SELLER = "virtualSeller",
    BUYER = "buyer",
    PHYSICAL_SELLER_PENDING = "physicalSellerPending"
}

export enum ApplicationStatus {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected"
}

export enum StoreType {
    PHYSICAL_STORE = "physicalStore",
    VIRTUAL_STORE = "virtualStore"
}

export enum Status {
    ACTIVE = "active",
    DRAFT = "draft",
    ARCHIVED = "archived"
}

export enum InputType {
    TEXT = "text",
    COLOR = "color",
    RANGE = "range",
    NUMBER = "number",
    SELECT = "select",
    MULTISELECT = "multiselect",
    BOOLEAN = "boolean"
}

export enum Type {
    SIMPLE = "simple",
    GROUPED = "grouped"
}

export type UsersData = Models.Document & {
    fullName: string;
    email: string;
    phoneNumber: string | null;
    accountType: AccountType;
    applicationStatus: ApplicationStatus | null;
    applicationReviewedAt: string | null;
    applicationReviewedBy: string | null;
    applicationReviewNotes: string | null;
    roleChangedAt: string | null;
    roleChangedBy: string | null;
    roleChangeReason: string | null;
    previousRole: string | null;
    businessName: string | null;
    businessAddress: string | null;
    businessPhone: string | null;
    applicationReason: string | null;
}

export type VirtualStore = Models.Document & {
    storeName: string;
    desccription: string | null;
    storeBio: string | null;
    bannerUrls: string[] | null;
    bannerIds: string[] | null;
    storeType: StoreType | null;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    subDomain: string;
    locale: string | null;
    owner: string;
    virtualProductsIds: string[] | null;
    operatingCountries: string[] | null;
}

export type PhysicalStore = Models.Document & {
    storeName: string;
    description: string | null;
    bio: string | null;
    owner: string;
    latitude: number;
    longitude: number;
    address: string;
    country: string;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    createdFrom: string | null;
    currency: string;
}

export type PhysicalProducts = Models.Document & {
    storeId: string;
    name: string;
    description: string;
    shortDescription: string | null;
    sku: string;
    basePrice: number;
    status: Status;
    featured: boolean;
    categoryId: string;
    subcategoryId: string;
    productTypeId: string;
    tags: string[] | null;
    weight: number | null;
    dimensions: string | null;
    hasVariants: boolean;
    variantIds: string[] | null;
    combinationIds: string[] | null;
    images: string[] | null;
    storeLat: number;
    storeLong: number;
    storeOriginCountry: string;
    createdBy: string;
    currency: string;
}

export type ProductVariants = Models.Document & {
    productId: string;
    templateId: string;
    name: string;
    inputType: InputType;
    values: string;
    required: boolean;
    sortOrder: number | null;
}

export type ProductCombinations = Models.Document & {
    productId: string;
    variantStrings: string[] | null;
    sku: string;
    price: number;
    stockQuantity: number | null;
    isActive: boolean;
    weight: number | null;
    dimensions: string | null;
    images: string[] | null;
    virtualCombinationPrices: VirtualCombinationPrices;
}

export type VariantOptions = Models.Document & {
    variantId: string;
    value: string | null;
    label: string | null;
    colorCode: string | null;
    additionalPrice: number | null;
    isDefault: boolean;
}

export type VariantCombinationValues = Models.Document & {
    combinationId: string;
    variantTemplateId: string | null;
    value: string | null;
}

export type VirtualProducts = Models.Document & {
    originalProductId: string;
    createdBy: string;
    virtualStoreId: string;
    sellingPrice: number;
    purchasePrice: number;
    currency: string | null;
    generalImageUrls: string[] | null;
    mainProdCommission: number;
    combinationPricesIds: string[] | null;
}

export type VirtualCombinationPrices = Models.Document & {
    virtualProductId: string;
    combinationId: string;
    combination: ProductCombinations;
    basePrice: number;
    commission: number;
    finalPrice: number;
}

export type ProductsCategories = Models.Document & {
    categoryName: string;
    iconUrl: string | null;
    storeId: string | null;
    createdBy: string;
    slug: string;
    isActive: boolean;
    sortOrder: number | null;
    iconFileId: string | null;
}

export type ProductsCollections = Models.Document & {
    collectionName: string;
    createdBy: string;
    storeId: string | null;
    bannerImageUrl: string | null;
    description: string | null;
    type: Type;
    featured: boolean;
    bannerImageId: string | null;
    groups: string[] | null;
    productsIds: string[] | null;
    heroTitle: string | null;
    heroSubtitle: string | null;
    heroDescription: string | null;
    heroButtonText: string | null;
    heroImageUrl: string | null;
}

export type ProductsCollectionGroups = Models.Document & {
    groupImageUrl: string | null;
    groupImageId: string | null;
    groupName: string | null;
    displayOrder: number | null;
    collectionId: string | null;
}

export type SavedItems = Models.Document & {
    userId: string;
    productId: string;
}

export type Subcategories = Models.Document & {
    categoryId: string;
    createdBy: string;
    isActive: boolean;
    slug: string | null;
    subCategoryName: string;
    iconUrl: string | null;
    iconFileId: string | null;
    parentCategoryId: string;
    productTypes: string[] | null;
}
