import { type Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types Z:\DATA\ARSENE\2025\ikazestore-new\ikazestores\src\lib\types\appwrite\appwrite.d.ts`.

export enum AccountType {
    SYS_ADMIN = "sysAdmin",
    SYS_AGENT = "sysAgent",
    PHYSICAL_SELLER = "physicalSeller",
    VIRTUAL_SELLER = "virtualSeller",
    BUYER = "buyer",
    PHYSICAL_SELLER_PENDING = "physicalSellerPending"
}

export enum ApplicationStatus {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected"
}

export enum StoreType {
    PHYSICAL_STORE = "physicalStore",
    VIRTUAL_STORE = "virtualStore"
}

export enum Status {
    ACTIVE = "active",
    DRAFT = "draft",
    ARCHIVED = "archived"
}

export enum InputType {
    TEXT = "text",
    COLOR = "color",
    RANGE = "range",
    NUMBER = "number",
    SELECT = "select",
    MULTISELECT = "multiselect",
    BOOLEAN = "boolean"
}

export enum Type {
    SIMPLE = "simple",
    GROUPED = "grouped"
}

export enum Status {
    ACTIVE = "active",
    DRAFT = "draft",
    ARCHIVED = "archived"
}

export enum StoreType {
    PHYSICAL_STORE = "physicalStore",
    VIRTUAL_STORE = "virtualStore"
}

export enum Status {
    ACTIVE = "active",
    DRAFT = "draft",
    ARCHIVED = "archived"
}

export enum Status {
    PENDING = "pending",
    PROCESSING = "processing",
    SHIPPED = "shipped",
    DELIVERED = "delivered",
    CANCELLED = "cancelled"
}

export enum CommissionStatus {
    PENDING = "pending"
}

export enum PhysicalStoreFulfillmentOrderStatus {
    PENDING_FULFILLMENT = "pending_fulfillment",
    PROCESSING = "processing",
    SHIPPED = "shipped",
    COMPLETED = "completed",
    CANCELLED = "cancelled"
}

export enum Status {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected",
    FLAGGED = "flagged"
}

export enum VirtualStoreReviewStatus {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected"
}

export enum ReviewType {
    PRODUCT = "product",
    STORE = "store"
}

export enum UserType {
    CUSTOMER = "customer",
    STORE_OWNER = "store_owner",
    ADMIN = "admin"
}

export enum Status {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected"
}

export enum ReviewType {
    PRODUCT = "product",
    STORE = "store",
    REPLY = "reply"
}

export enum VoteType {
    HELPFUL = "helpful",
    UNHELPFUL = "unhelpful"
}

export enum ReviewType {
    PRODUCT = "product",
    STORE = "store",
    REPLY = "reply"
}

export enum Reason {
    SPAM = "spam",
    INAPPROPRIATE = "inappropriate",
    FAKE = "fake",
    OFFENSIVE = "offensive",
    OTHER = "other"
}

export enum Status {
    PENDING = "pending",
    RESOLVED = "resolved",
    DISMISSED = "dismissed"
}

export type UsersData = Models.Document & {
    fullName: string;
    email: string;
    phoneNumber: string | null;
    accountType: AccountType;
    applicationStatus: ApplicationStatus | null;
    applicationReviewedAt: string | null;
    applicationReviewedBy: string | null;
    applicationReviewNotes: string | null;
    roleChangedAt: string | null;
    roleChangedBy: string | null;
    roleChangeReason: string | null;
    previousRole: string | null;
    businessName: string | null;
    businessAddress: string | null;
    businessPhone: string | null;
    applicationReason: string | null;
    bio: string | null;
    website: string | null;
}

export type VirtualStore = Models.Document & {
    storeName: string;
    desccription: string | null;
    storeBio: string | null;
    bannerUrls: string[] | null;
    bannerIds: string[] | null;
    storeType: StoreType | null;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    subDomain: string;
    locale: string | null;
    owner: string;
    virtualProductsIds: string[] | null;
    operatingCountries: string[] | null;
}

export type PhysicalStore = Models.Document & {
    storeName: string;
    description: string | null;
    bio: string | null;
    owner: string;
    latitude: number;
    longitude: number;
    address: string;
    country: string;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    createdFrom: string | null;
    currency: string;
}

export type PhysicalProducts = Models.Document & {
    storeId: string;
    name: string;
    description: string;
    shortDescription: string | null;
    sku: string;
    basePrice: number;
    status: Status;
    featured: boolean;
    categoryId: string;
    subcategoryId: string;
    productTypeId: string;
    tags: string[] | null;
    weight: number | null;
    dimensions: string | null;
    hasVariants: boolean;
    variantIds: string[] | null;
    combinationIds: string[] | null;
    images: string[] | null;
    storeLat: number;
    storeLong: number;
    storeOriginCountry: string;
    createdBy: string;
    currency: string;
}

export type ProductVariants = Models.Document & {
    productId: string;
    templateId: string;
    name: string;
    inputType: InputType;
    values: string;
    required: boolean;
    sortOrder: number | null;
}

export type ProductCombinations = Models.Document & {
    productId: string;
    variantStrings: string[] | null;
    sku: string;
    stockQuantity: number | null;
    isActive: boolean;
    weight: number | null;
    dimensions: string | null;
    images: string[] | null;
    basePrice: number;
    colorVariantId: string | null;
}

export type VariantOptions = Models.Document & {
    variantId: string;
    value: string | null;
    label: string | null;
    colorCode: string | null;
    additionalPrice: number | null;
    isDefault: boolean | null;
}

export type VariantCombinationValues = Models.Document & {
    combinationId: string;
    variantTemplateId: string | null;
    value: string | null;
}

export type VirtualProducts = Models.Document & {
    originalProductId: string;
    createdBy: string;
    virtualStoreId: string;
    sellingPrice: number;
    purchasePrice: number;
    currency: string | null;
    generalImageUrls: string[] | null;
    mainProdCommission: number;
    combinationPricesIds: string[] | null;
}

export type VirtualCombinationPrices = Models.Document & {
    virtualProductId: string;
    combinationId: string;
    basePrice: number;
    commission: number;
    finalPrice: number;
}

export type ProductCategories = Models.Document & {
    categoryName: string;
    iconUrl: string | null;
    storeId: string | null;
    createdBy: string;
    slug: string;
    isActive: boolean;
    sortOrder: number | null;
    iconFileId: string | null;
}

export type ProductCollections = Models.Document & {
    collectionName: string;
    createdBy: string;
    storeId: string | null;
    bannerImageUrl: string | null;
    description: string | null;
    type: Type;
    featured: boolean | null;
    bannerImageId: string | null;
    groups: string[] | null;
    productsIds: string[] | null;
    heroTitle: string | null;
    heroSubtitle: string | null;
    heroDescription: string | null;
    heroButtonText: string | null;
    heroImageUrl: string | null;
}

export type ProductCollectionGroups = Models.Document & {
    groupImageUrl: string | null;
    groupImageId: string | null;
    groupName: string | null;
    displayOrder: number | null;
    collectionId: string | null;
}

export type SavedItems = Models.Document & {
    userId: string;
    productId: string;
}

export type Subcategories = Models.Document & {
    categoryId: string;
    createdBy: string;
    isActive: boolean;
    slug: string | null;
    subCategoryName: string;
    iconUrl: string | null;
    iconFileId: string | null;
    parentCategoryId: string;
    productTypes: string[] | null;
}

export type PhysicalProducts = Models.Document & {
    storeId: string;
    name: string;
    description: string;
    shortDescription: string | null;
    sku: string;
    basePrice: number;
    status: Status;
    featured: boolean;
    categoryId: string;
    subcategoryId: string;
    productTypeId: string;
    tags: string[] | null;
    weight: number | null;
    dimensions: string | null;
    hasVariants: boolean;
    variantIds: string[] | null;
    combinationIds: string[] | null;
    images: string[] | null;
    storeLat: number;
    storeLong: number;
    storeOriginCountry: string;
    createdBy: string;
    currency: string;
}

export type AffiliateProductImports = Models.Document & {
    virtualStoreId: string;
    productId: string;
    isActive: boolean;
    importedAt: string;
    lastSyncedAt: string | null;
    commission: number;
    featured: boolean | null;
    virtualStoreName: string;
}

export type AffiliateCombinationPricing = Models.Document & {
    affiliateImportId: string;
    combinationId: string;
    customCommission: number | null;
    isActive: boolean;
}

export type ProductColors = Models.Document & {
    productId: string;
    colorName: string;
    colorCode: string;
    additionalPrice: number | null;
    isDefault: boolean | null;
    images: string[] | null;
}

export type Kkk = Models.Document & {
}

export type VirtualStore = Models.Document & {
    storeName: string;
    desccription: string | null;
    storeBio: string | null;
    bannerUrls: string[] | null;
    bannerIds: string[] | null;
    storeType: StoreType | null;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    subDomain: string;
    locale: string | null;
    owner: string;
    virtualProductsIds: string[] | null;
    operatingCountries: string[] | null;
}

export type PhysicalStore = Models.Document & {
    storeName: string;
    description: string | null;
    bio: string | null;
    owner: string;
    latitude: number;
    longitude: number;
    address: string;
    country: string;
    storeLogoId: string | null;
    storeLogoUrl: string | null;
    createdFrom: string | null;
    currency: string;
}

export type VirtualProducts = Models.Document & {
    originalProductId: string;
    createdBy: string;
    virtualStoreId: string;
    sellingPrice: number;
    purchasePrice: number;
    currency: string | null;
    generalImageUrls: string[] | null;
    mainProdCommission: number;
    combinationPricesIds: string[] | null;
}

export type ProductCategories = Models.Document & {
    categoryName: string;
    iconUrl: string | null;
    storeId: string | null;
    createdBy: string;
    slug: string;
    isActive: boolean | null;
    sortOrder: number | null;
    iconFileId: string | null;
}

export type Subcategories = Models.Document & {
    categoryId: string;
    createdBy: string;
    isActive: boolean;
    slug: string | null;
    subCategoryName: string;
    iconUrl: string | null;
    iconFileId: string | null;
    parentCategoryId: string;
    productTypes: string[] | null;
}

export type Products = Models.Document & {
    physicalStoreId: string;
    name: string;
    description: string;
    shortDescription: string | null;
    sku: string;
    basePrice: number;
    currency: string;
    status: Status;
    featured: boolean;
    categoryId: string;
    subcategoryId: string;
    productTypeId: string;
    tags: string[] | null;
    images: string[] | null;
    hasVariants: boolean;
    isDropshippingEnabled: boolean;
    createdBy: string;
    storeLatitude: number;
    storeLongitude: number;
    storeCountry: string;
}

export type Orders = Models.Document & {
    orderNumber: string;
    customerId: string;
    customerEmail: string | null;
    virtualStoreId: string;
    customerCurrency: string;
    customerSubtotal: number;
    customerTotalAmount: number;
    baseCurrency: string | null;
    baseSubtotal: number | null;
    baseTotalAmount: number | null;
    exchangeRateToBase: number | null;
    exchangeRatesTimestamp: string | null;
    totalCommission: number | null;
    totalBasePrice: number | null;
    deliveryAddress: string | null;
    notes: string | null;
    isExpressDelivery: boolean;
    paymentMethod: string;
    status: Status;
    orderDate: string;
    estimatedDeliveryDate: string | null;
    itemCount: number | null;
    exchangeRatesSnapshot: string | null;
    deliveredAt: string | null;
}

export type OrderItems = Models.Document & {
    orderId: string;
    virtualProductId: string;
    originalProductId: string;
    productName: string;
    productImage: string | null;
    sku: string;
    basePrice: number;
    sellingPrice: number;
    commission: number;
    quantity: number | null;
    subtotal: number;
    virtualStoreId: string;
    physicalStoreId: string;
}

export type CommissionRecord = Models.Document & {
    orderId: string;
    virtualStoreId: string;
    totalCommission: number;
    commissionStatus: CommissionStatus;
}

export type OrderFullfilmentRecords = Models.Document & {
    orderId: string;
    physicalStoreId: string;
    itemCount: number | null;
    totalValue: number | null;
    physicalStoreFulfillmentOrderStatus: PhysicalStoreFulfillmentOrderStatus;
}

export type ProductReview = Models.Document & {
    productId: string;
    virtualStoreId: string;
    userId: string;
    rating: number;
    title: string | null;
    comment: string | null;
    pros: string[] | null;
    cons: string[] | null;
    isVerifiedPurchase: boolean | null;
    orderId: string | null;
    images: string[] | null;
    videos: string[] | null;
    status: Status;
    moderatedBy: string | null;
    moderatedAt: string | null;
    moderationNotes: string | null;
    replies: number | null;
    lastReplyAt: string | null;
    viewCount: number | null;
    shareCount: number | null;
    userName: string;
    helpfulVotes: number | null;
    unhelpfulVotes: number | null;
    orderAmount: number | null;
    orderCurrency: string | null;
    purchaseDate: string | null;
}

export type VirtualstoreReviews = Models.Document & {
    virtualStoreId: string;
    overallRating: number;
    title: string | null;
    comment: string | null;
    customerServiceRating: number | null;
    isVerifiedCustomer: boolean;
    orderCount: number | null;
    virtualStoreReviewStatus: VirtualStoreReviewStatus | null;
    moderatedBy: string | null;
    moderatedAt: string | null;
    userId: string;
    userName: string;
}

export type ReviewReply = Models.Document & {
    reviewId: string;
    reviewType: ReviewType;
    replyingUserId: string;
    userName: string;
    userType: UserType;
    comment: string | null;
    helpfulVotes: number | null;
    unhelpfulVotes: number | null;
    status: Status;
    moderatedBy: string | null;
    moderatedAt: string | null;
}

export type ReviewVote = Models.Document & {
    reviewId: string;
    reviewType: ReviewType;
    userId: string;
    voteType: VoteType;
}

export type ReviewReport = Models.Document & {
    reviewId: string;
    reviewType: ReviewType;
    reportedBy: string;
    reason: Reason;
    description: string | null;
    status: Status;
    resolvedBy: string | null;
    resolvedAt: string | null;
}
